services:
  frontend:
    build: ./Teebay-FE
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
    - ./Teebay-FE:/app
    - /app/node_modules
  backend:
    build: ./Teebay-BE
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
    - ./Teebay-BE:/app
    - /app/node_modules
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: teebay
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: test1234
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "testuser", "-d", "teebay"]
      interval: 5s
      retries: 5
volumes:
  postgres-data: